trigger:
  branches:
    include:
      - main
      - Development
      - release/*
  paths:
    include:
      - 'Database.Projects/slfd-serverless-dw'


pool: 
  vmimage: windows-latest


variables:
  Devops_Service_Connection_Name: 'Sandbox - PAYG'
  Devops_Service_Principal: 'ee797751-c283-4f26-a4e4-87a0116197cb'
  Primary_EntraID_Admin_Email: 'leek@the-sandbox.co.uk'  #Variable for UPN of Entra ID Admin
  Primary_EntraID_Admin_SID: 'eb5001b9-8346-476a-b26a-77952ce01f70'
  Azure_Subscription_Id: '262069d1-4249-43a7-acc3-55714500fc42' #Variable for Azure Subscription ID
  Azure_Tenant_Id: '3dccfdf8-200b-47e3-afff-4a495b603cc2'
  Azure_Resource_Location: 'ukwest'
  Azure_Resource_Location_Formatted: 'UK West'

stages:

- stage: Pooldacpac
  displayName: 'Build dacpac'

  jobs:
    - job: 'Builddacpac'
      displayName: 'Build SLFD Serverless dacpac'
      
      steps:
     
      - task: VSBuild@1
        displayName: 'Builds the dacpac'
        inputs:
          solution: Database.Projects\slfd-serverless-dw\slfd-serverless-dw.sqlproj
          configuration: release

      - task: PublishBuildArtifacts@1
        displayName: 'Publishes dacpac as an artifact'
        inputs:
          PathtoPublish: 'Database.Projects\slfd-serverless-dw\bin\release'
          ArtifactName: slfd-serverless-dw
          publishLocation: 'Container'

- stage: SLFDDeployDev
  variables:
  - group: SLFD - Secure Development Variables
  displayName: 'Synapse Link for DV Deploy Dev'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/Development')
  jobs:
  - deployment: 'SLFDDeployDev'
    displayName: 'SLFD Serverless SQL Pool Dev'
    environment: Development

    pool: 
      vmimage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Dowload Artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'specific'
                artifactName:  'slfd-serverless-dw'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: SqlAzureDacpacDeployment@1
              displayName: 'Install DACPAC on dedicated SQL Pool'
              inputs:
                azureSubscription: $(Devops_Service_Connection_Name)
                AuthenticationType: 'server'
                ServerName: $(AZ_SynapseWorkspace_Name)-ondemand.sql.azuresynapse.net
                DatabaseName: $(AZ_SynapseWorkspace_SQL_Serverless_DbName)
                SqlUsername: $(AZ_SynapseWorkspace_SQL_Local_Username)
                SqlPassword: $(AZ_SynapseWorkspace_SQL_Local_Password)
                deployType: 'DacpacTask'
                DeploymentAction: 'Publish'
                DacpacFile: '$(System.ArtifactsDirectory)/slfd-serverless-dw/slfd-serverless-dw.dacpac'
                IpDetectionMethod: 'AutoDetect'

- stage: SLFDDeployUAT
  variables:
  - group: SLFD - Secure UAT Variables
  displayName: 'Synapse Link for DV Deploy UAT'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - deployment: 'SLFDDeployDev'
    displayName: 'SLFD Serverless SQL Pool UAT'
    environment: Development

    pool: 
      vmimage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Dowload Artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'specific'
                artifactName:  'slfd-serverless-dw'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: SqlAzureDacpacDeployment@1
              displayName: 'Install DACPAC on dedicated SQL Pool'
              inputs:
                azureSubscription: $(Devops_Service_Connection_Name)
                AuthenticationType: 'server'
                ServerName: $(AZ_SynapseWorkspace_Name)-ondemand.sql.azuresynapse.net
                DatabaseName: $(AZ_SynapseWorkspace_SQL_Serverless_DbName)
                SqlUsername: $(AZ_SynapseWorkspace_SQL_Local_Username)
                SqlPassword: $(AZ_SynapseWorkspace_SQL_Local_Password)
                deployType: 'DacpacTask'
                DeploymentAction: 'Publish'
                DacpacFile: '$(System.ArtifactsDirectory)/slfd-serverless-dw/slfd-serverless-dw.dacpac'
                IpDetectionMethod: 'AutoDetect'

- stage: SLFDDeployProd
  variables:
  - group: SLFD - Secure Production Variables
  displayName: 'Synapse Link for DV Deploy Prod'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - deployment: 'SLFDDeployDev'
    displayName: 'SLFD Serverless SQL Pool Prod'
    environment: Development

    pool: 
      vmimage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Dowload Artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'specific'
                artifactName:  'slfd-serverless-dw'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: SqlAzureDacpacDeployment@1
              displayName: 'Install DACPAC on dedicated SQL Pool'
              inputs:
                azureSubscription: $(Devops_Service_Connection_Name)
                AuthenticationType: 'server'
                ServerName: $(AZ_SynapseWorkspace_Name)-ondemand.sql.azuresynapse.net
                DatabaseName: $(AZ_SynapseWorkspace_SQL_Serverless_DbName)
                SqlUsername: $(AZ_SynapseWorkspace_SQL_Local_Username)
                SqlPassword: $(AZ_SynapseWorkspace_SQL_Local_Password)
                deployType: 'DacpacTask'
                DeploymentAction: 'Publish'
                DacpacFile: '$(System.ArtifactsDirectory)/slfd-serverless-dw/slfd-serverless-dw.dacpac'
                IpDetectionMethod: 'AutoDetect'